var geojson = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "id": 1, "Nombre": "CRAI campus Sescelades", "Dies": "de dilluns a divendres", "Horari": "10-13 h","Informació": "La reobertura del CRAI és només per prestar els serveis de préstec prèvia reserva i devolució de documents." }, "geometry": { "type": "Point", "coordinates": [1.245145,41.132234] } },
{ "type": "Feature", "properties": { "id": 2, "Nombre": "CRAI campus Bellisens", "Dies": "dilluns, dimecres i divendres", "Horari": "10-13 h", "Informació": "La reobertura del CRAI és només per prestar els serveis de préstec prèvia reserva i devolució de documents." }, "geometry": { "type": "Point", "coordinates": [1.122973,41.144519] } },
{ "type": "Feature", "properties": { "id": 3, "Nombre": "CRAI campus Catalunya", "Dies": "de dilluns a divendres", "Horari": "10-13 h", "Informació": "La reobertura del CRAI és només per prestar els serveis de préstec prèvia reserva i devolució de documents." }, "geometry": { "type": "Point", "coordinates": [ 1.249483,41.122774] } },
{ "type": "Feature", "properties": { "id": 5, "Nombre": "CRAI campus Terres de l´Ebre", "Dies": "dimecres i divendres", "Horari": "10-13 h","Informació": "La reobertura del CRAI és només per prestar els serveis de préstec prèvia reserva i devolució de documents."}, "geometry": { "type": "Point", "coordinates": [0.521658,40.818895 ] } },
{ "type": "Feature", "properties": { "id": 4, "Nombre": "CRAI campus Vila-seca", "Dies": "dimecres i divendres", "Horari": "10-13 h","Informació": "La reobertura del CRAI és només per prestar els serveis de préstec prèvia reserva i devolució de documents." }, "geometry": { "type": "Point", "coordinates": [1.147270,41.102759] } },
{ "type": "Feature", "properties": { "id": 6, "Nombre": "CRAI campus Medicina i Ciències de la Salut", "Dies": "dilluns, dimecres i divendres", "Horari": "10-13 h","Informació": "La reobertura del CRAI és només per prestar els serveis de préstec prèvia reserva i devolució de documents." }, "geometry": { "type": "Point", "coordinates": [1.105121,41.155450] } },
{ "type": "Feature", "properties": { "id": 8, "Nombre": "CRAI seu Baix Penedès", "Dies": "Tancat", "Horari": "-----","Informació": "La reobertura del CRAI és només per prestar els serveis de préstec prèvia reserva i devolució de documents." }, "geometry": { "type": "Point", "coordinates": [1.530194,41.182548 ] } },
{ "type": "Feature", "properties": { "id": 7, "Nombre": "CRAI Espai Aprenentatge de Llengües", "Dies": "1987", "Horari": "10-13 h","Informació": "La reobertura del CRAI és només per prestar els serveis de préstec prèvia reserva i devolució de documents." }, "geometry": { "type": "Point", "coordinates": [1.249483,41.122774 ] } },
{ "type": "Feature", "properties": { "id": 12, "Nombre": "CRAI Factoria", "Dies": "1987", "Horari": "10-13 h","Informació": "La reobertura del CRAI és només per prestar els serveis de préstec prèvia reserva i devolució de documents." }, "geometry": { "type": "Point", "coordinates": [1.249483, 41.122774 ] } },
{ "type": "Feature", "properties": { "id": 13, "Nombre": "CRAI campus Catalunya", "Dies": "de dilluns a divendres", "Horari": "10-13 h","Informació": "La reobertura del CRAI és només per prestar els serveis de préstec prèvia reserva i devolució de documents." }, "geometry": { "type": "Point", "coordinates": [1.249483,41.122774] } }
]
}
